### ISSUE TITLE
passing filenames to pre-commit hook

### ISSUE THREAD

**Issue by yarnabrina** [jendrikseipp/vulture#280]
I tried to use `vulture` as part of our `.pre-commmit-config.yaml` file. I added the following snippet directly as documented in [README](https://github.com/jendrikseipp/vulture/blob/master/README.md#version-control-integration):

```yaml
repos:
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'  # or any later Vulture version
    hooks:
      - id: vulture
```

It failed with the following error:

> Please pass at least one file or directory

While I fixed it by passing `.` as an argument in `args` section or by using `pass_filenames: true`, I feel this is a general enough to be included as part of the hook definition. Can you please change this?

https://github.com/jendrikseipp/vulture/blob/master/.pre-commit-hooks.yaml#L7

Or, if there are any issues with that, is it possible to at least update the documentation with a working snippet? I think that will be very helpful for other users.
