### ISSUE TITLE
Feature request: A way to more specifically target items for whitelisting

### ISSUE THREAD

**Issue by Hubro** [jendrikseipp/vulture#343]
I'm trying to implement Vulture for a big project at work that uses a proprietary application framework.

Entrypoints into the application are classes with a specific name (`Main`) that are subclasses of a specific framework class (`acme_corp.application.Service`) placed in a very specifically named module (e.g. `my_package_name/main.py`). The framework also has hooks, which are defined as methods with very specific names in subclasses of a specific framework class.

This is a very large codebase, and simply whitelisting the names `Main`, `_.before`, `_.after` etc. is likely to hit much more than just the entrypoints that I want to whitelist.

It would be tremendously useful if Vulture leveraged the AST to allow even more specific whitelists. You could take into account the type of object (if it's a constant, variable, class, method, function etc.), the location (file name, module name, package name), the base classes and so on.

To maintain backwards compatability, this could be added as a new feature, for example:

**pyproject.toml**:

```toml
[tool.vulture]

paths = "packages/"

entrypoints = [
    # Any class named "Main" in a module whose name ends with ".main" that is a
    # subclass of "acme_corp.application.Application"
    {
        type = "class",
        name = "Main",
        base_classes = ["acme_corp.application.Application"],
        module_name = "/\\.main$/",
    },

    # Any method named "create", "pre_hook" or "post_hook" in a class like the
    # one above
    {
        type = "method",
        name = ["create", "pre_hook", "post_hook"],
        parent_class = {
            name = "Main",
            base_classes = ["acme_corp.application.Application"],
            module_name = "/\\.main$/",
        }
    },

    # Any method named "pre_hook" or "post_hook" in a subclass of
    # "acme_corp.application.Service". (The class itself is *not* whitelisted.)
    {
        type = "method",
        name = ["pre_hook", "post_hook"],
        parent_class = {
            base_classes = ["acme_corp.application.Service"],
        }
    },

    # Class attributes named "name_prefix" in subclasses of
    # "acme_corp.application.Service". (The class itself is *not* whitelisted.)
    {
        type = "class_attribute",
        name = "name_prefix",
        parent_class = {
            base_classes = ["acme_corp.application.Service"],
        }
    },
]
```

Alternative names: `mark_used`, `tag`, (?)
